### ISSUE TITLE
Add basic emitters

### ISSUE THREAD

**Issue by solnic** [dkubb/sql#1]
- [x] "insert"
- [x] "delete"
- [x] "update"
- [x] "select"

**Comment by solnic** [comment]
@mbj I assigned this to you since I've no idea what we need

**Comment by dkubb** [comment]
@mbj if you want to outline a summary of how you'd approach this I can take care of it.

**Comment by mbj** [comment]
Sorry guys, I'm just too busy. 

Summary:
- Use a bottom up approach. In detail: Define high level targets and than break them down according to the SQL spec, till we covered the dependencies of the high level target.
- Rename already existing nodes according to the names used in the SQL spec, to greatly simplify searching the spec
- Win.

Warning:

The SQL spec I talk about is in BNF, in an AST we do not mirror the BNF! Example

```
numchar ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
integer ::= numchar [ number ]
```

We'd only have an integer node, no "numchar" nodes inside the integer one. Rule of thumb: We only need nodes that carry declarative semantics, not the details. We should have **just** enough information to reproduce an equivalent, but not identical source. `s(:integer, 123)` NOT `s(:integer, s(:numchar, '1') ...)`

IMHO we should focus on the following high level nodes, in this particular order:
- INSERT, this one is most easy, needs literals
- DELETE, this one is also easy, additionally needs restrictions
- UPDATE, dependencies are just like DELETE + assignment expressions
- SELECT, we can reuse restrictions but need lots of other nodes.
- Set operations (UNION, ...) needs SELECT
- JOIN, needs SELECT

**Comment by dkubb** [comment]
@mbj sounds great. I've got this.

**Comment by dkubb** [comment]
@mbj I've started on the renaming of the nodes. In some cases the node names in the BNF grammar don't make a ton of sense to me, so I will probably skip renaming them, but I will still try to rename anything where it makes sense.

For example, there's no node named "integer" exactly. The one we'd need to represent integers is named "signed integer". I suppose it makes sense in the context of an SQL parser, where you might define rules to match an unsigned integer, and then use that to build up a rule to match a date. However I think it's unlikely we'd represent a date in the AST as `s(:date, s(:unsigned_integer, 2013), s(:unsigned_integer, 1), s(:unsigned_integer, 1))`. Based on what I know we'd be more likely to represent a date using `s(:date, Date.new(2013, 1, 1))`.

If this is what you were talking about above I understand what you mean now. ;)

**Comment by mbj** [comment]
@dkubb Yeah, _if_ we have a primitive we should use it. So I'd also do `s(:date, Date.new(2013, 1, 1)`.

**Comment by solnic** [comment]
closing this one since I added basic insert/select/update/delete emitters
